#!/usr/bin/env python

import os
import sys
import time
import psutil

def get_cpu_usage():
    cpu_percent = psutil.cpu_percent(interval=1)
    return cpu_percent

def get_memory_usage():
    mem = psutil.virtual_memory()
    return mem.percent

def get_disk_usage():
    disk = psutil.disk_usage("/")
    return disk.percent

def monitor_performance():
    cpu_usage = get_cpu_usage()
    mem_usage = get_memory_usage()
    disk_usage = get_disk_usage()
    
    return (cpu_usage, mem_usage, disk_usage)

if __name__ == "__main__":
    while True:
        performance_data = monitor_performance()
        print("CPU Usage: {}%, Memory Usage: {}%, Disk Usage: {}%".format(*performance_data))
        time.sleep(60)
